import { Image } from 'expo-image';
import { useEffect, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import logo from '../../assets/images/enggxr-logo.png';
import { getRecommendations, hasApi, MobileCollege, saveProfile, updateRemoteShortlist } from '../lib/api';
import { clearAppState, loadAppState, saveAppState } from '../lib/storage';

type Stage = 'public' | 'onboarding' | 'app';
type Tab = 'Home' | 'Explore' | 'Matches' | 'Profile';
type College = MobileCollege;

const C = { deep:'#071116', ink:'#0D171C', cyan:'#08BDB7', cyanSoft:'#D7F6F3', canvas:'#F5F8F7', white:'#FCFEFD', text:'#142323', muted:'#5E7270', line:'#D5E0DE', amber:'#D28A13' };
const colleges: College[] = [
  { id:1, short:'JNTUH', name:'JNTUH University College of Engineering', branch:'CSE', location:'Hyderabad', category:'Target', match:83, probability:67, fee:'INR 1.2L', pkg:'INR 8.4L', reason:'The branch, fee, and commute match your current profile.' },
  { id:2, short:'VNR', name:'VNR VJIET', branch:'Data Science', location:'Bachupally', category:'Safe', match:87, probability:85, fee:'INR 1.35L', pkg:'INR 7.8L', reason:'The sample cutoff gives this option a higher admission estimate.' },
  { id:3, short:'CBIT', name:'CBIT Hyderabad', branch:'AI and ML', location:'Gandipet', category:'Dream', match:77, probability:44, fee:'INR 1.6L', pkg:'INR 9.1L', reason:'The branch matches your goals, but the sample cutoff is ambitious.' },
];
const tabs: Tab[] = ['Home','Explore','Matches','Profile'];

export default function EnggXRMobile() {
  const [ready,setReady]=useState(false);
  const [stage,setStage]=useState<Stage>('public');
  const [tab,setTab]=useState<Tab>('Home');
  const [step,setStep]=useState(1);
  const [name,setName]=useState('Arjun Sharma');
  const [rank,setRank]=useState('4523');
  const [budget,setBudget]=useState('150000');
  const [shortlisted,setShortlisted]=useState<number[]>([1]);
  const [results,setResults]=useState<College[]>(colleges);
  const [dataState,setDataState]=useState<'sample'|'loading'|'live'|'offline'>('sample');
  const {width}=useWindowDimensions();

  useEffect(()=>{loadAppState().then(saved=>{if(saved){setStage(saved.stage);setName(saved.name);setRank(saved.rank);setBudget(saved.budget);setShortlisted(saved.shortlisted)}setReady(true)}).catch(()=>setReady(true))},[]);
  useEffect(()=>{if(ready)saveAppState({stage,name,rank,budget,shortlisted}).catch(()=>undefined)},[ready,stage,name,rank,budget,shortlisted]);

  const finishOnboarding=async()=>{
    setStage('app');setTab('Matches');
    if(!hasApi){setDataState('sample');return}
    setDataState('loading');
    try{await saveProfile(name,rank,budget);setResults(await getRecommendations());setDataState('live')}catch{setResults(colleges);setDataState('offline')}
  };
  const toggleShortlist=(id:number)=>{setShortlisted(items=>{const selected=!items.includes(id);updateRemoteShortlist(id,selected).catch(()=>undefined);return selected?[...items,id]:items.filter(x=>x!==id)})};
  const reset=async()=>{await clearAppState();setStage('public');setTab('Home');setStep(1);setName('');setRank('');setBudget('');setShortlisted([]);setResults(colleges);setDataState('sample')};

  if(!ready)return <SafeAreaView style={s.loading}><ActivityIndicator color={C.cyan}/><Text style={s.loadingText}>Loading EnggXR</Text></SafeAreaView>;
  if(stage==='public') return <PublicEntry onStart={()=>setStage('onboarding')} onDemo={()=>setStage('app')}/>;
  if(stage==='onboarding') return <Onboarding step={step} name={name} rank={rank} budget={budget} onName={setName} onRank={setRank} onBudget={setBudget} onBack={()=>step===1?setStage('public'):setStep(step-1)} onNext={()=>step<3?setStep(step+1):finishOnboarding()}/>;
  return <SafeAreaView style={s.appSafe} edges={['top']}><View style={[s.frame,width>=720&&s.tablet]}><Header name={name}/><View style={s.body}>{tab==='Home'&&<Home name={name} rank={rank} onMatches={()=>setTab('Matches')}/>} {tab==='Explore'&&<Explore/>} {tab==='Matches'&&<Matches colleges={results} dataState={dataState} shortlisted={shortlisted} onToggle={toggleShortlist}/>} {tab==='Profile'&&<Profile name={name} rank={rank} budget={budget} onReset={reset}/>}</View><BottomNav tab={tab} onChange={setTab}/></View></SafeAreaView>;
}

function PublicEntry({onStart,onDemo}:{onStart:()=>void;onDemo:()=>void}){
  return <SafeAreaView style={s.publicSafe}><ScrollView contentContainerStyle={s.publicScroll} showsVerticalScrollIndicator={false}><Logo/><View style={s.hero}><Text style={s.kicker}>ENGINEERING ADMISSIONS, MADE CLEAR</Text><Text style={s.heroTitle}>Choose a college with the facts in front of you.</Text><Text style={s.heroBody}>Enter your rank, branch interests, and budget. Review college matches with the reason for each result.</Text><Primary label="Build my shortlist" onPress={onStart}/><Pressable style={s.textButton} onPress={onDemo}><Text style={s.textButtonLabel}>View sample results</Text></Pressable></View><View style={s.example}><View style={s.exampleHead}><Text style={s.panelLabel}>EXAMPLE RESULT</Text><Text style={s.panelMeta}>EAPCET</Text></View><Text style={s.exampleRank}>Rank 4,523</Text><View style={s.exampleRow}><View style={s.flex}><Text style={s.exampleCollege}>VNR - Data Science</Text><Text style={s.exampleReason}>Higher estimate in sample cutoff data</Text></View><Text style={s.exampleScore}>87%</Text></View><Text style={s.disclaimer}>Sample data only. Admission estimates are not guarantees.</Text></View><View style={s.factStrip}><Text style={s.fact}>Admission chance</Text><Text style={s.fact}>Fees and ROI</Text><Text style={s.fact}>Branch fit</Text></View></ScrollView></SafeAreaView>;
}

function Onboarding(p:{step:number;name:string;rank:string;budget:string;onName:(v:string)=>void;onRank:(v:string)=>void;onBudget:(v:string)=>void;onBack:()=>void;onNext:()=>void}){
  const labels=['Student','EAPCET','Budget'];
  const valid=p.step===1?p.name.trim().length>=2:p.step===2?Number(p.rank)>0:Number(p.budget)>0;
  const error=p.step===1?'Enter at least 2 characters.':p.step===2?'Enter a valid positive rank.':'Enter a valid annual tuition budget.';
  return <SafeAreaView style={s.formSafe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.formHeader}><Pressable style={s.back} onPress={p.onBack} accessibilityLabel="Go back"><Text style={s.backText}>&lt;-</Text></Pressable><Logo compact/><Text style={s.stepCount}>{p.step}/3</Text></View><View style={s.progress}>{labels.map((label,i)=><View key={label} style={s.progressItem}><View style={[s.bar,i<p.step&&s.barActive]}/><Text style={[s.progressText,i<p.step&&s.progressTextActive]}>{label}</Text></View>)}</View><ScrollView contentContainerStyle={s.formContent} keyboardShouldPersistTaps="handled">{p.step===1&&<><Title title="Tell us about the student" intro="Use the name shown on counselling documents."/><Field label="Full name" value={p.name} onChange={p.onName} placeholder="Student name"/></>}{p.step===2&&<><Title title="Add the EAPCET rank" intro="This is compared with demonstration closing ranks."/><Field label="EAPCET rank" value={p.rank} onChange={p.onRank} placeholder="Example: 4523" numeric/></>}{p.step===3&&<><Title title="Set an annual budget" intro="Include tuition only. Hostel and travel can be added later."/><Field label="Annual tuition in INR" value={p.budget} onChange={p.onBudget} placeholder="Example: 150000" numeric/><View style={s.review}><Text style={s.reviewLabel}>PROFILE SUMMARY</Text><Text style={s.reviewValue}>{p.name} - Rank {Number(p.rank||0).toLocaleString('en-IN')}</Text></View></>}{!valid&&<Text style={s.validation}>{error}</Text>}</ScrollView><View style={s.formFooter}><Primary label={p.step===3?'Show matches':'Continue'} onPress={p.onNext} disabled={!valid}/></View></KeyboardAvoidingView></SafeAreaView>;
}

function Title({title,intro}:{title:string;intro:string}){return <><Text style={s.formTitle}>{title}</Text><Text style={s.formIntro}>{intro}</Text></>}
function Field({label,value,onChange,placeholder,numeric=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;numeric?:boolean}){return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput style={s.input} value={value} onChangeText={t=>onChange(numeric?t.replace(/[^0-9]/g,''):t)} placeholder={placeholder} placeholderTextColor="#839491" keyboardType={numeric?'number-pad':'default'}/></View>}
function Logo({compact=false}:{compact?:boolean}){return <Image source={logo} style={compact?s.logoSmall:s.logo} contentFit="contain"/>}
function Primary({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable style={[s.primary,disabled&&s.primaryDisabled]} onPress={onPress} disabled={disabled} accessibilityRole="button" accessibilityState={{disabled}}><Text style={s.primaryText}>{label}</Text><Text style={s.arrow}>-&gt;</Text></Pressable>}

function Header({name}:{name:string}){return <View style={s.header}><Logo compact/><View style={s.headerRight}><View><Text style={s.headerLabel}>STUDENT PROFILE</Text><Text style={s.headerName}>{name.split(' ')[0]||'Student'}</Text></View><View style={s.avatar}><Text style={s.avatarText}>{(name[0]||'S').toUpperCase()}</Text></View></View></View>}
function Screen({children}:{children:React.ReactNode}){return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}>{children}</ScrollView>}
function ScreenTitle({kicker,title,intro}:{kicker:string;title:string;intro:string}){return <><Text style={s.screenKicker}>{kicker}</Text><Text style={s.screenTitle}>{title}</Text><Text style={s.screenIntro}>{intro}</Text></>}

function Home({name,rank,onMatches}:{name:string;rank:string;onMatches:()=>void}){return <Screen><ScreenTitle kicker="DECISION SUMMARY" title={`Good morning, ${name.split(' ')[0]||'Student'}.`} intro="Your rank is compared with the current demonstration dataset."/><View style={s.rankPanel}><Text style={s.rankLabel}>EAPCET RANK</Text><Text style={s.rankValue}>{Number(rank||0).toLocaleString('en-IN')}</Text><Text style={s.rankNote}>38 sample college-branch combinations</Text></View><Text style={s.sectionTitle}>Next actions</Text><Action n="01" title="Review college matches" detail="Compare estimate, cost, and branch fit." onPress={onMatches}/><Action n="02" title="Confirm annual budget" detail="Improve the financial-fit calculation."/><Action n="03" title="Build preference order" detail="Keep Dream, Target, and Safe choices."/></Screen>}
function Action({n,title,detail,onPress}:{n:string;title:string;detail:string;onPress?:()=>void}){return <Pressable style={s.action} onPress={onPress}><Text style={s.actionN}>{n}</Text><View style={s.flex}><Text style={s.actionTitle}>{title}</Text><Text style={s.actionDetail}>{detail}</Text></View><Text style={s.actionArrow}>-&gt;</Text></Pressable>}

function Explore(){const branches=[['Computer Science',98,'Very high'],['AI and Machine Learning',94,'Growing'],['Data Science',89,'High'],['Electronics and Communication',77,'Stable']] as const;return <Screen><ScreenTitle kicker="BRANCH COMPARISON" title="Compare engineering branches." intro="Scores use the interests selected in the sample profile."/>{branches.map((b,i)=><View key={b[0]} style={s.branch}><Text style={s.branchN}>0{i+1}</Text><View style={s.flex}><Text style={s.branchName}>{b[0]}</Text><Text style={s.branchMeta}>Career outlook: {b[2]}</Text><View style={s.track}><View style={[s.fill,{width:`${b[1]}%`}]}/></View></View><Text style={s.branchScore}>{b[1]}</Text></View>)}</Screen>}

function Matches({colleges,dataState,shortlisted,onToggle}:{colleges:College[];dataState:'sample'|'loading'|'live'|'offline';shortlisted:number[];onToggle:(id:number)=>void}){const label=dataState==='live'?'LIVE API RESULTS':dataState==='loading'?'CALCULATING MATCHES':dataState==='offline'?'OFFLINE SAMPLE RESULTS':'SAMPLE RESULTS';return <Screen><ScreenTitle kicker={label} title="College matches for your profile." intro="Results use your rank, interests, budget, and commute preferences."/><View style={s.notice}><Text style={s.noticeTitle}>{dataState==='loading'?'Getting your recommendations':'How to read these results'}</Text><Text style={s.noticeText}>{dataState==='loading'?'The app is checking the EnggXR service.':'Percentages use demonstration cutoffs. They are not admission guarantees.'}</Text>{dataState==='loading'&&<ActivityIndicator style={s.inlineLoader} color={C.cyan}/>}</View>{colleges.map((c,i)=><CollegeRow key={c.id} c={c} i={i} selected={shortlisted.includes(c.id)} onToggle={()=>onToggle(c.id)}/>)}</Screen>}
function CollegeRow({c,i,selected,onToggle}:{c:College;i:number;selected:boolean;onToggle:()=>void}){const [open,setOpen]=useState(false);return <View style={s.college}><View style={s.collegeTop}><Text style={s.resultN}>0{i+1}</Text><View style={s.collegeIdentity}><Text style={s.category}>{c.category.toUpperCase()}</Text><Text style={s.collegeName}>{c.name}</Text><Text style={s.collegeMeta}>{c.branch} - {c.location}</Text></View><View style={s.match}><Text style={s.matchValue}>{c.match}%</Text><Text style={s.matchLabel}>MATCH</Text></View></View><Text style={s.reason}>{c.reason}</Text><View style={s.metrics}><Metric label="Admission" value={`${c.probability}%`}/><Metric label="Annual fee" value={c.fee}/><Metric label="Avg. package" value={c.pkg}/></View>{open&&<View style={s.detailPanel}><Text style={s.detailTitle}>Estimate context</Text><Text style={s.detailCopy}>This match combines the demonstration cutoff position, tuition fit, branch preference, and sample placement data. Verify all figures with official counselling sources before making a decision.</Text></View>}<View style={s.actions}><Pressable style={[s.shortlist,selected&&s.shortlistOn]} onPress={onToggle} accessibilityRole="button" accessibilityState={{selected}}><Text style={[s.shortlistText,selected&&s.shortlistTextOn]}>{selected?'Shortlisted':'Add to shortlist'}</Text></Pressable><Pressable style={s.details} onPress={()=>setOpen(value=>!value)} accessibilityRole="button" accessibilityState={{expanded:open}}><Text style={s.detailsText}>{open?'Hide details':'View details'}</Text><Text style={s.detailsArrow}>{open?'^':'v'}</Text></Pressable></View></View>}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}

function Profile({name,rank,budget,onReset}:{name:string;rank:string;budget:string;onReset:()=>void}){return <Screen><ScreenTitle kicker="PROFILE" title="Recommendation inputs" intro="Update these values when counselling details change."/><View style={s.profileHead}><View style={s.profileAvatar}><Text style={s.profileAvatarText}>{(name[0]||'S').toUpperCase()}</Text></View><View><Text style={s.profileName}>{name||'Student'}</Text><Text style={s.profileMeta}>EAPCET applicant</Text></View></View><ProfileRow label="EAPCET rank" value={Number(rank||0).toLocaleString('en-IN')}/><ProfileRow label="Annual tuition budget" value={`INR ${Number(budget||0).toLocaleString('en-IN')}`}/><ProfileRow label="Preferred branches" value="CSE, AI and ML"/><ProfileRow label="Accommodation" value="Either"/><Text style={s.dataNote}>Profile and shortlist data are saved on this device.</Text><Pressable style={s.resetButton} onPress={onReset} accessibilityRole="button"><Text style={s.resetText}>Reset app data</Text></Pressable></Screen>}
function ProfileRow({label,value}:{label:string;value:string}){return <View style={s.profileRow}><Text style={s.profileRowLabel}>{label}</Text><Text style={s.profileRowValue}>{value}</Text></View>}
function BottomNav({tab,onChange}:{tab:Tab;onChange:(t:Tab)=>void}){return <SafeAreaView edges={['bottom']} style={s.bottomSafe}><View style={s.bottomNav}>{tabs.map(item=><Pressable key={item} style={s.tab} onPress={()=>onChange(item)} accessibilityRole="tab" accessibilityState={{selected:item===tab}}><View style={[s.tabIcon,item===tab&&s.tabIconOn]}><Text style={[s.tabLetter,item===tab&&s.tabLetterOn]}>{item[0]}</Text></View><Text style={[s.tabLabel,item===tab&&s.tabLabelOn]}>{item}</Text></Pressable>)}</View></SafeAreaView>}

const s=StyleSheet.create({
  flex:{flex:1},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:14,backgroundColor:C.deep},loadingText:{color:C.white,fontSize:14,fontWeight:'700'},publicSafe:{flex:1,backgroundColor:C.canvas},publicScroll:{paddingHorizontal:20,paddingTop:12,paddingBottom:40},logo:{width:150,height:54},logoSmall:{width:118,height:43},hero:{paddingTop:56,gap:18},kicker:{color:C.muted,fontSize:11,lineHeight:15,letterSpacing:1.3,fontWeight:'800'},heroTitle:{color:C.text,fontSize:40,lineHeight:44,letterSpacing:-1.6,fontWeight:'800',maxWidth:560},heroBody:{color:C.muted,fontSize:17,lineHeight:27,maxWidth:580},primary:{minHeight:52,paddingHorizontal:20,backgroundColor:C.cyan,borderRadius:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},primaryText:{color:C.deep,fontSize:16,fontWeight:'800'},arrow:{color:C.deep,fontSize:18,fontWeight:'800'},textButton:{minHeight:48,justifyContent:'center',alignItems:'center'},textButtonLabel:{color:C.text,fontSize:15,fontWeight:'700',textDecorationLine:'underline'},example:{marginTop:52,padding:22,borderRadius:14,backgroundColor:C.ink,gap:20},exampleHead:{flexDirection:'row',justifyContent:'space-between'},panelLabel:{color:C.cyan,fontSize:10,letterSpacing:1.2,fontWeight:'800'},panelMeta:{color:'#9EB2B1',fontSize:11},exampleRank:{color:C.white,fontSize:30,fontWeight:'800',letterSpacing:-.8},exampleRow:{paddingVertical:18,borderTopWidth:1,borderBottomWidth:1,borderColor:'#294047',flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:16},exampleCollege:{color:C.white,fontSize:15,fontWeight:'800'},exampleReason:{color:'#9EB2B1',fontSize:12,marginTop:5,maxWidth:240},exampleScore:{color:C.cyan,fontSize:17,fontWeight:'800'},disclaimer:{color:'#829492',fontSize:11,lineHeight:17},factStrip:{paddingVertical:28,flexDirection:'row',justifyContent:'space-between',gap:8},fact:{color:C.muted,fontSize:11,fontWeight:'700',flex:1,textAlign:'center'},
  formSafe:{flex:1,backgroundColor:C.canvas},formHeader:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:48,height:48,borderRadius:8,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},backText:{fontSize:18,color:C.text,fontWeight:'800'},stepCount:{width:48,textAlign:'right',color:C.muted,fontWeight:'700'},progress:{flexDirection:'row',gap:8,paddingHorizontal:20,paddingTop:16},progressItem:{flex:1,gap:7},bar:{height:3,backgroundColor:C.line},barActive:{backgroundColor:C.cyan},progressText:{color:'#8A9A98',fontSize:10},progressTextActive:{color:C.text,fontWeight:'700'},formContent:{flexGrow:1,paddingHorizontal:20,paddingTop:58,paddingBottom:32},formTitle:{color:C.text,fontSize:32,lineHeight:38,letterSpacing:-1,fontWeight:'800'},formIntro:{color:C.muted,fontSize:16,lineHeight:25,marginTop:12,marginBottom:36},field:{gap:9},fieldLabel:{color:C.text,fontSize:13,fontWeight:'800'},input:{minHeight:54,paddingHorizontal:15,borderWidth:1,borderColor:'#BFCFCD',borderRadius:8,backgroundColor:C.white,color:C.text,fontSize:16},review:{marginTop:28,paddingVertical:18,borderTopWidth:1,borderBottomWidth:1,borderColor:C.line,gap:6},reviewLabel:{color:C.muted,fontSize:11,fontWeight:'800',letterSpacing:1},reviewValue:{color:C.text,fontSize:15,fontWeight:'700'},validation:{color:'#A23A3A',fontSize:13,lineHeight:19,marginTop:18},formFooter:{paddingHorizontal:20,paddingTop:12,paddingBottom:16,borderTopWidth:1,borderColor:C.line,backgroundColor:C.canvas},primaryDisabled:{opacity:.45},
  appSafe:{flex:1,backgroundColor:C.canvas},frame:{flex:1,backgroundColor:C.canvas},tablet:{width:'100%',maxWidth:820,alignSelf:'center',borderLeftWidth:1,borderRightWidth:1,borderColor:C.line},header:{minHeight:68,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:C.line,backgroundColor:C.white},headerRight:{flexDirection:'row',alignItems:'center',gap:10},headerLabel:{color:C.muted,fontSize:8,letterSpacing:.8,fontWeight:'800',textAlign:'right'},headerName:{color:C.text,fontSize:13,fontWeight:'800',textAlign:'right',marginTop:2},avatar:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center',backgroundColor:C.ink},avatarText:{color:C.cyan,fontSize:15,fontWeight:'800'},body:{flex:1},screen:{paddingHorizontal:18,paddingTop:30,paddingBottom:36},screenKicker:{color:C.cyan,fontSize:10,letterSpacing:1.1,fontWeight:'800'},screenTitle:{color:C.text,fontSize:30,lineHeight:36,letterSpacing:-1,fontWeight:'800',marginTop:10},screenIntro:{color:C.muted,fontSize:15,lineHeight:23,marginTop:10,marginBottom:28},rankPanel:{backgroundColor:C.ink,padding:22,borderRadius:14,gap:8,marginBottom:38},rankLabel:{color:C.cyan,fontSize:10,letterSpacing:1.1,fontWeight:'800'},rankValue:{color:C.white,fontSize:44,letterSpacing:-1.5,fontWeight:'800'},rankNote:{color:'#9EB2B1',fontSize:12},sectionTitle:{color:C.text,fontSize:20,fontWeight:'800',marginBottom:12},action:{minHeight:84,flexDirection:'row',alignItems:'center',gap:13,borderTopWidth:1,borderColor:C.line},actionN:{width:28,color:'#8A9A98',fontSize:11,fontWeight:'800'},actionTitle:{color:C.text,fontSize:15,fontWeight:'800'},actionDetail:{color:C.muted,fontSize:12,lineHeight:18,marginTop:4},actionArrow:{color:C.cyan,fontSize:16,fontWeight:'800'},
  branch:{minHeight:106,paddingVertical:18,flexDirection:'row',alignItems:'center',gap:12,borderTopWidth:1,borderColor:C.line},branchN:{color:'#8A9A98',fontSize:11,fontWeight:'800'},branchName:{color:C.text,fontSize:16,fontWeight:'800'},branchMeta:{color:C.muted,fontSize:12,marginTop:5},track:{height:4,backgroundColor:'#DCE6E4',marginTop:14},fill:{height:4,backgroundColor:C.cyan},branchScore:{width:32,color:C.text,fontSize:17,fontWeight:'800',textAlign:'right'},notice:{paddingVertical:18,borderTopWidth:1,borderBottomWidth:1,borderColor:C.line,marginBottom:20},noticeTitle:{color:C.text,fontSize:13,fontWeight:'800'},noticeText:{color:C.muted,fontSize:12,lineHeight:18,marginTop:5},
  college:{paddingVertical:24,borderBottomWidth:1,borderColor:C.line},collegeTop:{flexDirection:'row',alignItems:'flex-start',gap:10},resultN:{width:24,color:'#8A9A98',fontSize:10,fontWeight:'800',paddingTop:3},collegeIdentity:{flex:1},category:{color:C.amber,fontSize:9,letterSpacing:1,fontWeight:'900'},collegeName:{color:C.text,fontSize:17,lineHeight:22,fontWeight:'800',marginTop:7},collegeMeta:{color:C.muted,fontSize:12,marginTop:5},match:{width:58,alignItems:'flex-end'},matchValue:{color:C.cyan,fontSize:18,fontWeight:'900'},matchLabel:{color:C.muted,fontSize:8,fontWeight:'800',marginTop:2},reason:{color:C.muted,fontSize:13,lineHeight:20,marginTop:18,paddingLeft:34},metrics:{flexDirection:'row',marginTop:20,marginLeft:34,borderTopWidth:1,borderBottomWidth:1,borderColor:C.line},metric:{flex:1,paddingVertical:14,gap:5},metricLabel:{color:C.muted,fontSize:9},metricValue:{color:C.text,fontSize:12,fontWeight:'800'},detailPanel:{marginTop:18,marginLeft:34,padding:16,backgroundColor:'#EAF0EF',borderRadius:8,gap:7},detailTitle:{color:C.text,fontSize:12,fontWeight:'800'},detailCopy:{color:C.muted,fontSize:12,lineHeight:19},actions:{flexDirection:'row',gap:10,marginTop:18,marginLeft:34},shortlist:{minHeight:48,flex:1,borderWidth:1,borderColor:C.line,borderRadius:8,alignItems:'center',justifyContent:'center'},shortlistOn:{borderColor:C.cyan,backgroundColor:C.cyanSoft},shortlistText:{color:C.text,fontSize:12,fontWeight:'800'},shortlistTextOn:{color:'#087A76'},details:{minHeight:48,flex:1,borderRadius:8,backgroundColor:C.ink,paddingHorizontal:13,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},detailsText:{color:C.white,fontSize:12,fontWeight:'800'},detailsArrow:{color:C.cyan,fontSize:14,fontWeight:'800'},inlineLoader:{marginTop:14,alignSelf:'flex-start'},
  profileHead:{minHeight:92,flexDirection:'row',alignItems:'center',gap:14,borderTopWidth:1,borderColor:C.line},profileAvatar:{width:58,height:58,borderRadius:29,alignItems:'center',justifyContent:'center',backgroundColor:C.ink},profileAvatarText:{color:C.cyan,fontSize:22,fontWeight:'800'},profileName:{color:C.text,fontSize:18,fontWeight:'800'},profileMeta:{color:C.muted,fontSize:12,marginTop:4},profileRow:{minHeight:72,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:16,borderTopWidth:1,borderColor:C.line},profileRowLabel:{color:C.muted,fontSize:13,flex:1},profileRowValue:{color:C.text,fontSize:14,fontWeight:'800',textAlign:'right',flex:1},dataNote:{color:C.muted,fontSize:11,lineHeight:17,marginTop:24},resetButton:{minHeight:48,marginTop:28,borderWidth:1,borderColor:C.line,borderRadius:8,alignItems:'center',justifyContent:'center'},resetText:{color:C.text,fontSize:13,fontWeight:'800'},bottomSafe:{backgroundColor:C.deep},bottomNav:{minHeight:66,flexDirection:'row',backgroundColor:C.deep,borderTopWidth:1,borderColor:'#294047'},tab:{flex:1,minHeight:62,alignItems:'center',justifyContent:'center',gap:4},tabIcon:{width:27,height:24,borderRadius:5,alignItems:'center',justifyContent:'center'},tabIconOn:{backgroundColor:'#15383D'},tabLetter:{color:'#819492',fontSize:11,fontWeight:'900'},tabLetterOn:{color:C.cyan},tabLabel:{color:'#819492',fontSize:10,fontWeight:'700'},tabLabelOn:{color:C.cyan},
});
